In [17]:
import nltk
import numpy as np
import sklearn as sk

In [18]:
# nltk.download()

In [19]:
f=open('chatbot2.txt','r',errors = 'ignore')
raw=f.read()
raw=raw.lower()# converts to lowercase
nltk.download('punkt') # first-time use only
nltk.download('wordnet') # first-time use only
sent_tokens = nltk.sent_tokenize(raw)# converts to list of sentences 
word_tokens = nltk.word_tokenize(raw)# converts to list of words

[nltk_data] Downloading package punkt to /Users/jim_jack/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/jim_jack/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [20]:
sent_tokens[:2]

['a chatbot is a computer program which conducts a conversation via auditory or textual methods.',
 '[1] such programs are often designed to convincingly simulate how a human would behave as a conversational partner, although as of 2019, they are far short of being able to pass the turing test.']

In [21]:
word_tokens[:5]

['a', 'chatbot', 'is', 'a', 'computer']

In [22]:
lemmer = nltk.stem.WordNetLemmatizer()
#WordNet is a semantically-oriented dictionary of English included in NLTK.
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [23]:
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up","hey",)
GREETING_RESPONSES = ["hi", "hey", "*nods*", "hi there", "hello", "I am glad! You are talking to me"]
def greeting(sentence):
 
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)


In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
def response(user_response):
    robo_response=''
    sent_tokens.append(user_response)
    TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
    tfidf = TfidfVec.fit_transform(sent_tokens)
    vals = cosine_similarity(tfidf[-1], tfidf)
    idx=vals.argsort()[0][-2]
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    if(req_tfidf==0):
        robo_response=robo_response+"I am sorry! I don't understand you"
        return robo_response
    else:
        robo_response = robo_response+sent_tokens[idx]
        return robo_response

In [30]:
flag=True
print("ROBO: My name is Robo. I will answer your queries about Chatbots. If you want to exit, type bye")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("ROBO: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("ROBO: "+greeting(user_response))
            else:
                print("ROBO: ",end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag=False
        print("ROBO: Bye! take care...")

ROBO: My name is Robo. I will answer your queries about Chatbots. If you want to exit, type Bye!
can you tell me about the design of a chatbot?
ROBO: by responding to any input that contains the word 'mother' with 'tell me more about your family').
chatbot
ROBO: [43]

hello barbie is an internet-connected version of the doll that uses a chatbot provided by the company toytalk,[44] which previously used the chatbot for a range of smartphone-based characters for children.
barbie
ROBO: [43]

hello barbie is an internet-connected version of the doll that uses a chatbot provided by the company toytalk,[44] which previously used the chatbot for a range of smartphone-based characters for children.
bye
ROBO: Bye! take care...


## Playing with the response function

In [31]:
def response(user_response):
    robo_response=''
    sent_tokens.append(user_response)
    TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
    tfidf = TfidfVec.fit_transform(sent_tokens)
    vals = cosine_similarity(tfidf[-1], tfidf)
    idx=vals.argsort()[0][-2]
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    if(req_tfidf==0):
        robo_response=robo_response+"I am sorry! I don't understand you"
        return robo_response
    else:
        robo_response = robo_response+sent_tokens[idx]
        return robo_response

In [33]:
#user search
user_response = 'Tell me about barbie chatbots'
#placeholder response
robo_response = ''

In [37]:
sent_tokens

['a chatbot is a computer program which conducts a conversation via auditory or textual methods.',
 '[1] such programs are often designed to convincingly simulate how a human would behave as a conversational partner, although as of 2019, they are far short of being able to pass the turing test.',
 '[2] chatbots are typically used in dialog systems for various practical purposes including customer service or information acquisition.',
 'some chatbots use sophisticated natural language processing systems, but many simpler ones scan for keywords within the input, then pull a reply with the most matching keywords, or the most similar wording pattern, from a database.',
 'the term "chatterbot" was originally coined by michael mauldin (creator of the first verbot, julia) in 1994 to describe these conversational programs.',
 "[3] today, most chatbots are accessed via virtual assistants such as google assistant and amazon alexa, via messaging apps such as facebook messenger or wechat, or via i

In [38]:
sent_tokens.append(user_response)

In [39]:
TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')

In [40]:
TfidfVec

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<function LemNormalize at 0x1a239aabf8>, use_idf=True,
        vocabulary=None)

In [41]:
tfidf = TfidfVec.fit_transform(sent_tokens)
tfidf

/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


<122x937 sparse matrix of type '<class 'numpy.float64'>'
	with 1618 stored elements in Compressed Sparse Row format>

In [42]:
?tfidf

In [43]:
vals = cosine_similarity(tfidf[-1], tfidf)

In [46]:
vals

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [47]:
vals.shape

(1, 122)

In [54]:
vals[0][-2]

0.0

In [49]:
vals.argsort()

array([[  0,  88,  87,  86,  84,  83,  82,  81,  80,  79,  78,  77,  76,
         89,  75,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,
         62,  74,  90,  91,  92, 119, 118, 117, 116, 115, 114, 113, 112,
        111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,
         98,  97,  96,  95,  94,  93,  61, 120,  60,  58,  27,  26,  25,
         24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,
         11,  10,   9,   8,   7,   6,   5,   4,   3,   2,   1,  28,  59,
         29,  31,  57,  56,  55,  54,  53,  52,  51,  50,  49,  48,  47,
         46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,
         33,  32,  30,  85, 121]])

In [48]:
idx=vals.argsort()[0][-2]
idx

85

In [57]:
vals.flatten().shape

(122,)

In [58]:
vals.flatten()

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [59]:
flat = vals.flatten()

In [60]:
flat.sort()

In [61]:
flat

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [62]:
req_tfidf = flat[-2]